name = "LeroyCompilerVerificationCourse"
version = "0.1.0"
defaultTargets = ["LeroyCompilerVerificationCourse"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.22.0-rc2"

[[lean_lib]]
name = "LeroyCompilerVerificationCourse"
leanOptions = [["grind.warning", false]]
