name = "LeroyCompilerVerificationCourse"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeroyCompilerVerificationCourse"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.21.0-rc3"

[[lean_lib]]
name = "LeroyCompilerVerificationCourse"
